#markdown: rdiscount
permalink: /:title/
url: http://fmzhao.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: fmz 
description: :))) | Stop talking, start doing.
author: fmz
email: fengmengzhao@gmail.com
duoshuo: fmz
weibo: 1891858481
hub: fmz 
safe: false
about: "热爱生命"
